version: '{build}'

platform: x64

image: Visual Studio 2019

environment:
  CONAN_RUN_TESTS: 1
  PYTHON: "C:\\Python37"

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip3.exe install conan
  - cmd: pip3.exe install conan_package_tools
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan profile new default --detect --force
  - cmd: conan profile show default

build_script:
  - cmd: mkdir build && cd build
  - cmd: conan install .. -b missing
  - cmd: conan build ..

test_script:
  - cmd: ctest