coverage:
  precision: 2
  round: nearest
  range: "60...90"
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        target: 80%
  ignore:
    - "**src/challenge.hpp"

codecov:
  branch: master

comment:
  layout: "diff"